name: Daily Crypto News Analysis

on:
  schedule:
    - cron: '0 6 * * *'  # Exécution tous les jours à 6h00 UTC
  workflow_dispatch:      # Permet aussi l'exécution manuelle

jobs:
  analyze-news:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas tweepy beautifulsoup4 telegram-send

    - name: Run news analyzer
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: python news_analyzer.py
