name: Data Collector

on:
  schedule:
    # Déclenchement toutes les heures
    - cron:  '0 * * * *'
  workflow_dispatch: 
    # Permet aussi de déclencher le workflow manuellement depuis l'interface GitHub

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.5'  # Choisis ta version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data collector
        run: |
          export BINANCE_API_KEY=${{ secrets.BINANCE_API_KEY }}
          export BINANCE_API_SECRET=${{ secrets.BINANCE_API_SECRET }}
          python data_collector.py
      
      - name: Run data collector
        run: |
          python data_collector.py
          
      # (Optionnel) Si tu veux sauvegarder les résultats de manière persistante :
      - name: Commit and push updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ETH_USDT_1h_raw.csv
          git commit -m "Update data [skip ci]"
          git push origin main
